spring:
  data:
    redis:
      host: localhost
      port: 6379
      #      password: redis
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 25
          min-idle: 5
          max-wait: 2000ms
