spring:
  profiles:
    include:
      - elasticsearch
      - loadbalancer
  application:
    name: tvr-search
  cloud:
    zookeeper:
      connect-string: localhost:2181
  config:
    import: optional:zookeeper:localhost:2181
server:
  port: 10005
---
spring:
  cloud:
    consul:
      discovery:
        instanceZone: zone1
  config:
    activate:
      on-profile: zone1
server:
  port: ${PORT:8091}

---
spring:
  cloud:
    consul:
      discovery:
        instanceZone: zone2
  config:
    activate:
      on-profile: zone1
server:
  port: ${PORT:9091}
