
elasticsearch:
  uri: http://127.0.0.1:9200
spring:
  elasticsearch:
    uris:
      - http://127.0.0.1:9200
    connection-timeout: 2s
    socket-timeout: 4s
  data:
    elasticsearch:
      repositories:
        enabled: true
