spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pg
    username: pg
    password: pg
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      idle-timeout: 30000
      validation-timeout: 3000
      connection-timeout: 3000
      max-lifetime: 60000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.treevalue.robot.user.mybatis.model
  global-config:
    db-config:
      id-type: auto
